version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - restore_cache:
         key: deps1-{{ .Branch }}-{{ cheksum "requeriments.txt"}}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requeriments.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ cheksum "requeriments.txt"}}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            .venv/bin/activate
            python3 test.py
      - store_artifacts:
          path: teste-reports/
          destination: python_app